### ISSUE TITLE
Crash happend when attach a empty dataSource

### ISSUE THREAD

**Issue by Vove7** [arcadefire/nice-spinner#112]
```
 java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at org.angmarch.views.NiceSpinnerAdapter.getItemInDataset(NiceSpinnerAdapter.java:54)
        at org.angmarch.views.NiceSpinner.setAdapterInternal(NiceSpinner.java:353)
        at org.angmarch.views.NiceSpinner.attachDataSource(NiceSpinner.java:336)
```

**Comment by arcadefire** [comment]
Fixed in 592b1b2daa7f4a91297db405ed135684f1d8a2e3.
