### ISSUE TITLE
Array index out of bound exception when using in recyclerview

### ISSUE THREAD

**Issue by jovanpreet** [arcadefire/nice-spinner#16]
Here is the logcat: 

```
FATAL EXCEPTION: main
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime: Process: com.dp.needdepartmentalstore1, PID: 24823
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime: java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at java.util.Arrays$ArrayList.get(Arrays.java:66)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at org.angmarch.views.NiceSpinnerAdapter.getItemInDataset(NiceSpinnerAdapter.java:36)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at org.angmarch.views.NiceSpinner.setAdapterInternal(NiceSpinner.java:232)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at org.angmarch.views.NiceSpinner.attachDataSource(NiceSpinner.java:222)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at com.dp.needdepartmentalstore.ProductsAdapter.onBindViewHolder(ProductsAdapter.java:89)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at com.dp.needdepartmentalstore.ProductsAdapter.onBindViewHolder(ProductsAdapter.java:25)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5212)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5245)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4483)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1161)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1018)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3807)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:549)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-14 17:29:11.667 24823-24823/com.dp.needdepartmentalstore1 E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

This occurs when we select different spinner value of particular cell and then scroll the recyclerview. Basically the mSelectedIndex of `nicespinner.java` doesn't get updated and holds the previous selected item index of different cell which generate out of bound exception.

**Comment by arcadefire** [comment]
Hello @jovanpreet, I'll give it a look asap, thank you!

**Comment by jovanpreet** [comment]
@arcadefire if you need my code implementation or anything else i will provide you. And by far your spinner is the best spinner. One more thing i am using [UltimateRecyclerView](https://github.com/cymcsg/UltimateRecyclerView)

**Comment by arcadefire** [comment]
@jovanpreet thank you! :)
I'll try a shot with that library you have linked and see what happens. I'll keep you updated.

**Comment by jovanpreet** [comment]
Hey @arcadefire any progress in this.

**Comment by arcadefire** [comment]
Hey, sorry, I was in very busy work weeks, I'll drop an eye in the upcoming weekend!

**Comment by arcadefire** [comment]
I pushed a commit on the dev branch that should solve the issue. Can you check @jovanpreet? Thanks!

**Comment by jovanpreet** [comment]
ok i will check and let you know
