### ISSUE TITLE
error occurred nullpointerexception if less down 24sdk

### ISSUE THREAD

**Issue by kinghom** [arcadefire/nice-spinner#31]
java.lang.NullPointerException
                                                                          at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:505)
                                                                          at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:487)
                                                                          at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:517)
                                                                          at android.animation.ValueAnimator.start(ValueAnimator.java:936)
                                                                          at android.animation.ValueAnimator.start(ValueAnimator.java:946)
                                                                          at android.animation.ObjectAnimator.start(ObjectAnimator.java:465)
                                                                          at org.angmarch.views.NiceSpinner.animateArrow(Unknown Source)
                                                                          at org.angmarch.views.NiceSpinner.showDropDown(Unknown Source)
                                                                          at org.angmarch.views.NiceSpinner.onTouchEvent(Unknown Source)
                                                                          at android.view.View.dispatchTouchEvent(View.java:7706)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
                                                                          at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
                                                                          at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
                                                                          at android.view.View.dispatchPointerEvent(View.java:7886)

**Comment by kinghom** [comment]
run in android 4.0.x  occurred error nullpointerexception

**Comment by arcadefire** [comment]
Hello, does this happen right away when you click on the spinner? I couldn't test on an api less that 16, but from JellyBeans on works without any issue.

**Comment by hanmeimei888** [comment]
i met this issue too、

**Comment by hanmeimei888** [comment]
it's happend when i use spinner on dialog  ,crash at click

**Comment by jiangwenn** [comment]
i met this problem in android 4.4 too, the problem was caused by `arrowDrawable` is null and `isArrowHidden` is true.

 i fix this problem by added the below code
```
mSpinner.attachDataSource(stringList);
mSpinner.setArrowDrawable(org.angmarch.views.R.drawable.arrow);
```

**Comment by George-Soros** [comment]
@jiangwenn tks for you，setArrowDrawable can finish this question!
