### ISSUE TITLE
nice-spinner not support in scrollview! the listview in popupwindow cannot scroll!

### ISSUE THREAD

**Issue by 475789729** [arcadefire/nice-spinner#38]

**Comment by comm1x** [comment]
+1

**Comment by hxk1224** [comment]
Can't use in Fragment ,It will crash.

11-15 15:55:48.470 14897-14897/com.wy.jx_mses E/InputEventReceiver: Exception dispatching input event.
11-15 15:55:48.470 14897-14897/com.wy.jx_mses E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
11-15 15:55:48.500 14897-14897/com.wy.jx_mses E/MessageQueue-JNI: java.lang.NullPointerException
                                                                      at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:505)
                                                                      at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:487)
                                                                      at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:522)
                                                                      at android.animation.ValueAnimator.start(ValueAnimator.java:941)
                                                                      at android.animation.ValueAnimator.start(ValueAnimator.java:957)
                                                                      at android.animation.ObjectAnimator.start(ObjectAnimator.java:465)
                                                                      at org.angmarch.views.NiceSpinner.animateArrow(NiceSpinner.java:334)
                                                                      at org.angmarch.views.NiceSpinner.showDropDown(NiceSpinner.java:346)
                                                                      at org.angmarch.views.NiceSpinner.onTouchEvent(NiceSpinner.java:321)
                                                                      at android.view.View.dispatchTouchEvent(View.java:7728)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)

**Comment by HulkHou** [comment]
I think it doesn't work at API 19.
At API24, it works.The same code.
