### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by hudan2714** [arcadefire/nice-spinner#70]
java.lang.NullPointerException
                                                                        at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:505)
                                                                        at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:459)
                                                                        at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:503)
                                                                        at android.animation.ValueAnimator.start(ValueAnimator.java:921)
                                                                        at android.animation.ValueAnimator.start(ValueAnimator.java:931)
                                                                        at android.animation.ObjectAnimator.start(ObjectAnimator.java:437)
                                                                        at org.angmarch.views.NiceSpinner.animateArrow(NiceSpinner.java:334)
                                                                        at org.angmarch.views.NiceSpinner.showDropDown(NiceSpinner.java:346)
                                                                        at org.angmarch.views.NiceSpinner.onTouchEvent(NiceSpinner.java:321)
                                                                        at android.view.View.dispatchTouchEvent(View.java:7817)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2326)
                                                                        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1612)
                                                                        at android.app.Activity.dispatchTouchEvent(Activity.java:2494)
                                                                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2274)
                                                                        at android.view.View.dispatchPointerEvent(View.java:8025)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4675)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4563)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4157)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4214)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4183)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4268)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4191)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4325)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4157)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4214)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4183)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4191)
                                                                    	at android.view.ViewRootImpl$InputStage.deliver

**Comment by Whatgbc** [comment]
i get it now,but it works on another place...
