### ISSUE TITLE
proguard config?

### ISSUE THREAD

**Issue by erlangp** [arcadefire/nice-spinner#95]
Logcat
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at org.angmarch.views.NiceSpinnerBaseAdapter.getView(NiceSpinnerBaseAdapter.java:60)
        at android.widget.AbsListView.obtainView(AbsListView.java:2369)
        at android.widget.ListView.measureHeightOfChildren(ListView.java:1327)
        at android.widget.ListView.onMeasure(ListView.java:1234)
        at android.view.View.measure(View.java:19757)
```

**Comment by erlangp** [comment]
```
buildTypes {
        debug {
            debuggable true
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            testProguardFiles getDefaultProguardFile("proguard-android.txt"), "proguardTest-rules.pro"
        }
}
```

**Comment by erlangp** [comment]
package org.angmarch.views;
NiceSpinnerBaseAdapter<T>

```java
textView.setText(this.spinnerTextFormatter.format(this.getItem(position).toString()));
```

**Comment by arunavo4** [comment]
add this line to your proguard rules

-keep class com.github.arcadefire.** { *; }
-dontwarn com.github.arcadefire.**

**Comment by arcadefire** [comment]
@erlangp did @arunavo4 suggestion solve your issue?
